server:
  port: 3000
  ssl:
    enable: false
    keyType: "PKCS12"
    p12KeyFile: "./certs/server.p12"
    p12KeyPassword: "password"
services:
  - path: "/orders"
    stripPath: true
    timeout: 60
    servers:
      - "http://localhost:3001"
      - "http://localhost:3002"