// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: plugin/proto/middleware.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiddlewarePlugin_HandleRequest_FullMethodName = "/zolly.plugin.MiddlewarePlugin/HandleRequest"
	MiddlewarePlugin_Configure_FullMethodName     = "/zolly.plugin.MiddlewarePlugin/Configure"
	MiddlewarePlugin_HealthCheck_FullMethodName   = "/zolly.plugin.MiddlewarePlugin/HealthCheck"
)

// MiddlewarePluginClient is the client API for MiddlewarePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiddlewarePluginClient interface {
	HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*ConfigureResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type middlewarePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewarePluginClient(cc grpc.ClientConnInterface) MiddlewarePluginClient {
	return &middlewarePluginClient{cc}
}

func (c *middlewarePluginClient) HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, MiddlewarePlugin_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewarePluginClient) Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, MiddlewarePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewarePluginClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MiddlewarePlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewarePluginServer is the server API for MiddlewarePlugin service.
// All implementations must embed UnimplementedMiddlewarePluginServer
// for forward compatibility.
type MiddlewarePluginServer interface {
	HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	Configure(context.Context, *PluginConfig) (*ConfigureResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMiddlewarePluginServer()
}

// UnimplementedMiddlewarePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiddlewarePluginServer struct{}

func (UnimplementedMiddlewarePluginServer) HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedMiddlewarePluginServer) Configure(context.Context, *PluginConfig) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedMiddlewarePluginServer) HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMiddlewarePluginServer) mustEmbedUnimplementedMiddlewarePluginServer() {}
func (UnimplementedMiddlewarePluginServer) testEmbeddedByValue()                          {}

// UnsafeMiddlewarePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddlewarePluginServer will
// result in compilation errors.
type UnsafeMiddlewarePluginServer interface {
	mustEmbedUnimplementedMiddlewarePluginServer()
}

func RegisterMiddlewarePluginServer(s grpc.ServiceRegistrar, srv MiddlewarePluginServer) {
	// If the following call panics, it indicates UnimplementedMiddlewarePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiddlewarePlugin_ServiceDesc, srv)
}

func _MiddlewarePlugin_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewarePluginServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewarePlugin_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewarePluginServer).HandleRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewarePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewarePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewarePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewarePluginServer).Configure(ctx, req.(*PluginConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewarePlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewarePluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewarePlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewarePluginServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MiddlewarePlugin_ServiceDesc is the grpc.ServiceDesc for MiddlewarePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiddlewarePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zolly.plugin.MiddlewarePlugin",
	HandlerType: (*MiddlewarePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRequest",
			Handler:    _MiddlewarePlugin_HandleRequest_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _MiddlewarePlugin_Configure_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MiddlewarePlugin_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/middleware.proto",
}
